name = "telegram-mcq-bot"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
account_id = "f086202cb2e3a8db18b1675a224b4799"

# Use workers.dev subdomain for deployment
workers_dev = true

[[kv_namespaces]]
binding = "STATE"
id = "9b9b1a3319f9445dbbe22388631f48bd"

[vars]
TZ = "Asia/Kolkata"

[triggers]
crons = ["0 * * * *"]
